# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
# To build on OSX, switch the previous line to
# language: objective-c
script: ./travis-tool.sh run_tests
env:
  global:
    - WARNINGS_ARE_ERRORS=1

before_script:
  - ./travis-tool.sh dump_sysinfo
after_success:
  - ./travis-tool.sh dump_logs_by_extension out
after_error:
  - ./travis-tool.sh dump_logs
after_failure:
  - cat ~/r-source/config.log || true
  - ./travis-tool.sh dump_logs

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - IsSourceInstall() { [[ -n "${RELEASE}" ]]; }
  - if IsSourceInstall; then export FORCE_SOURCE_INSTALL=1; fi
install:
  - if IsSourceInstall; then (
    sudo apt-get install --no-install-recommends texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra;
    cd ~ &&
    svn co -q https://svn.r-project.org/R/${RELEASE}/ r-source &&
    cd r-source &&
    tools/rsync-recommended &&
    R_BATCHSAVE="--no-save --no-restore"
      R_BROWSER=xdg-open
      PAGER=/usr/bin/pager
      PERL=/usr/bin/perl
      R_UNZIPCMD=/usr/bin/unzip
      R_ZIPCMD=/usr/bin/zip
      R_PRINTCMD=/usr/bin/lpr
      LIBnn=lib
      AWK=/usr/bin/awk
      CC=gcc
      CFLAGS="-ggdb -pipe -std=gnu99 -Wall -pedantic"
      CXX=g++
      CXXFLAGS="-ggdb -pipe -Wall -pedantic"
      FC=gfortran
      F77=gfortran
       ./configure --enable-R-shlib &&
     make -j2 &&
     sudo make install
   ); fi
  - ./travis-tool.sh r_binary_install RUnit inline highlight XML
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: always
